#ifndef AVMP_INTERPRETER_CONFIG_H
#define AVMP_INTERPRETER_CONFIG_H

#ifndef VM_ENABLE_DEBUG_TRACE
#define VM_ENABLE_DEBUG_TRACE 0
#endif

#if !VM_ENABLE_DEBUG_TRACE && defined(GOVM_CPP_DEBUG)
#undef GOVM_CPP_DEBUG
#endif

#define SEG_SIZE 5000
#define VM_CALL_STACK_MAX 256
#define VM_CRASH_TRACE_DEPTH 32
#define IS_INLINE_FUNC

#endif
